spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.10.145:31010
      password: nacos
      username: nacos
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000 #建立连接需要的时间
        readTimeout: 5000 #读取数据所需的时间